name: Convert YAML to JSON

on:
  push:
    paths:
      - 'anime/**/*.yml'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install yq
        run: |
          sudo apt-get update
          sudo apt-get install -y yq

      - name: Convert YAML to JSON
        run: |
          find animes -type f -name "*.yml" | while read -r file; do
            json_file="${file%.yml}.json"
            yq -o=json "$file" > "$json_file"
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add animes/**/*.json
          git commit -m "Convert YAML to JSON"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
