name: Convert YAML to JSON

on:
  push:
    paths:
      - 'anime/**/*.yml'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Convert YAML to JSON con Python puro
        run: |
            python -c '
            import yaml, json, os
            for root, _, files in os.walk("anime"):
                for file in files:
                    if file.endswith(".yml"):
                        yml_path = os.path.join(root, file)
                        json_path = yml_path.replace(".yml", ".json")
                        with open(yml_path, "r", encoding="utf-8") as yml_file:
                            data = yaml.safe_load(yml_file)
                        with open(json_path, "w", encoding="utf-8") as json_file:
                            json.dump(data, json_file, indent=2, ensure_ascii=False)
            '



      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add animes/**/*.json
          git commit -m "Convert YAML to JSON"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
