- uses: fabasoad/data-format-converter-action@v1.0.0
  with:
    # (Required) Pattern in glob format that would be used to list the files.
    source-pattern: "animes/**/*.yml"
    # (Optional) Data type of the source files. Possible values: json, xml, yaml,
    # props, lua. Defaults to the type defined by file extension.
    from: "yml"
    # (Required) Data type to be converted to. Possible values: json, xml, yaml,
    # props, lua.
    to: "json"