name: Convert YAML to JSON

on:
  push:
    paths:
      - 'anime/**/*.yml'
  workflow_dispatch:

jobs:
  convert:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python yq
        run: pip install --force-reinstall yq pyyaml

      - name: Convert YAML to JSON
        run: |
          python -m yq -p=yaml -o=json anime/**/*.yml


      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add animes/**/*.json
          git commit -m "Convert YAML to JSON"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
